[package]
name = "RustPKTester"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.4"
hex = "0.4.3"
log = "0.4.22"
log4rs = "1.3.0"
num_cpus = "1.16.0"
rand = "0.8.5"
rayon = "1.10.0"
rusqlite = "0.32.1"
